// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_events.sql

package sqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueActivityEvent = `-- name: EnqueueActivityEvent :one
INSERT INTO activity_events (
    external_id, user_id, object_type, aspect_type, object_id,
    owner_id, subscription_id, event_time, raw_payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (external_id) DO UPDATE SET
    external_id = EXCLUDED.external_id
RETURNING id, external_id, user_id, object_type, aspect_type, object_id, owner_id, subscription_id, event_time, received_at, processed_at, raw_payload
`

type EnqueueActivityEventParams struct {
	ExternalID     string             `json:"external_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ObjectType     string             `json:"object_type"`
	AspectType     string             `json:"aspect_type"`
	ObjectID       int64              `json:"object_id"`
	OwnerID        pgtype.Int8        `json:"owner_id"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	EventTime      pgtype.Timestamptz `json:"event_time"`
	RawPayload     []byte             `json:"raw_payload"`
}

func (q *Queries) EnqueueActivityEvent(ctx context.Context, arg EnqueueActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, enqueueActivityEvent,
		arg.ExternalID,
		arg.UserID,
		arg.ObjectType,
		arg.AspectType,
		arg.ObjectID,
		arg.OwnerID,
		arg.SubscriptionID,
		arg.EventTime,
		arg.RawPayload,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.UserID,
		&i.ObjectType,
		&i.AspectType,
		&i.ObjectID,
		&i.OwnerID,
		&i.SubscriptionID,
		&i.EventTime,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.RawPayload,
	)
	return i, err
}

const getActivityEventByID = `-- name: GetActivityEventByID :one
SELECT id, external_id, user_id, object_type, aspect_type, object_id, owner_id, subscription_id, event_time, received_at, processed_at, raw_payload
FROM activity_events
WHERE id = $1
`

func (q *Queries) GetActivityEventByID(ctx context.Context, id pgtype.UUID) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, getActivityEventByID, id)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.UserID,
		&i.ObjectType,
		&i.AspectType,
		&i.ObjectID,
		&i.OwnerID,
		&i.SubscriptionID,
		&i.EventTime,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.RawPayload,
	)
	return i, err
}

const getUserIDByAthleteID = `-- name: GetUserIDByAthleteID :one
SELECT user_id FROM strava_tokens WHERE athlete_id = $1 LIMIT 1
`

func (q *Queries) GetUserIDByAthleteID(ctx context.Context, athleteID int64) (pgtype.UUID, error) {
	var user_id pgtype.UUID
	err := q.db.QueryRow(ctx, getUserIDByAthleteID, athleteID).Scan(&user_id)
	// sqlc deja ErrNoRows crudo: lo aplanamos a (uuid inválido, nil) para
	// que el handler del PR B pueda hacer `if !uid.Valid { return }` sin
	// distinguir entre "atleta desconocido" y un error real de DB.
	// AUD-03 (issue #165) PR A.
	if errors.Is(err, pgx.ErrNoRows) {
		return pgtype.UUID{}, nil
	}
	return user_id, err
}

const listPendingActivityEvents = `-- name: ListPendingActivityEvents :many
SELECT id, external_id, user_id, object_type, aspect_type, object_id, owner_id, subscription_id, event_time, received_at, processed_at, raw_payload
FROM activity_events
WHERE processed_at IS NULL
ORDER BY received_at
LIMIT $1
`

func (q *Queries) ListPendingActivityEvents(ctx context.Context, limit int32) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, listPendingActivityEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityEvent
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.UserID,
			&i.ObjectType,
			&i.AspectType,
			&i.ObjectID,
			&i.OwnerID,
			&i.SubscriptionID,
			&i.EventTime,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.RawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActivityEventProcessed = `-- name: MarkActivityEventProcessed :exec
UPDATE activity_events
SET processed_at = now()
WHERE id = $1
`

func (q *Queries) MarkActivityEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markActivityEventProcessed, id)
	return err
}
