// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueActivityEvent = `-- name: EnqueueActivityEvent :one
INSERT INTO activity_events (
    user_id, object_type, aspect_type, object_id,
    owner_id, subscription_id, event_time, raw_payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (object_id, aspect_type, event_time) DO UPDATE SET
    object_id = EXCLUDED.object_id
RETURNING id, user_id, object_type, aspect_type, object_id, owner_id, subscription_id, event_time, received_at, processed_at, raw_payload
`

type EnqueueActivityEventParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	ObjectType     string             `json:"object_type"`
	AspectType     string             `json:"aspect_type"`
	ObjectID       int64              `json:"object_id"`
	OwnerID        pgtype.Int8        `json:"owner_id"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	EventTime      pgtype.Timestamptz `json:"event_time"`
	RawPayload     []byte             `json:"raw_payload"`
}

// Return the existing row when Strava retries the same natural event key.
func (q *Queries) EnqueueActivityEvent(ctx context.Context, arg EnqueueActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, enqueueActivityEvent,
		arg.UserID,
		arg.ObjectType,
		arg.AspectType,
		arg.ObjectID,
		arg.OwnerID,
		arg.SubscriptionID,
		arg.EventTime,
		arg.RawPayload,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectType,
		&i.AspectType,
		&i.ObjectID,
		&i.OwnerID,
		&i.SubscriptionID,
		&i.EventTime,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.RawPayload,
	)
	return i, err
}

const getActivityEventByID = `-- name: GetActivityEventByID :one
SELECT id, user_id, object_type, aspect_type, object_id, owner_id, subscription_id, event_time, received_at, processed_at, raw_payload FROM activity_events WHERE id = $1
`

// Load an event by the internal UUID passed to IngestActivityEventWorker.
func (q *Queries) GetActivityEventByID(ctx context.Context, id pgtype.UUID) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, getActivityEventByID, id)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectType,
		&i.AspectType,
		&i.ObjectID,
		&i.OwnerID,
		&i.SubscriptionID,
		&i.EventTime,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.RawPayload,
	)
	return i, err
}

const getUserIDByAthleteID = `-- name: GetUserIDByAthleteID :one
SELECT (
    SELECT user_id FROM strava_tokens WHERE athlete_id = $1 LIMIT 1
)::uuid AS user_id
`

// The scalar subquery always returns one row. An unknown athlete therefore
// scans as pgtype.UUID{Valid:false} rather than pgx.ErrNoRows.
func (q *Queries) GetUserIDByAthleteID(ctx context.Context, athleteID int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByAthleteID, athleteID)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listPendingActivityEvents = `-- name: ListPendingActivityEvents :many
SELECT id, user_id, object_type, aspect_type, object_id, owner_id, subscription_id, event_time, received_at, processed_at, raw_payload
FROM activity_events
WHERE processed_at IS NULL
ORDER BY received_at
LIMIT $1
`

// Lista los eventos pendientes (processed_at IS NULL) para alimentar un
// job de procesamiento. LIMIT defensivo para evitar scans descontrolados.
func (q *Queries) ListPendingActivityEvents(ctx context.Context, limit int32) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, listPendingActivityEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityEvent
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ObjectType,
			&i.AspectType,
			&i.ObjectID,
			&i.OwnerID,
			&i.SubscriptionID,
			&i.EventTime,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.RawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActivityEventProcessed = `-- name: MarkActivityEventProcessed :exec
UPDATE activity_events
SET processed_at = now()
WHERE id = $1
`

// Marca un evento como procesado una vez consumido por el job.
func (q *Queries) MarkActivityEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markActivityEventProcessed, id)
	return err
}
