// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueActivityEvent = `-- name: EnqueueActivityEvent :one
INSERT INTO activity_events (
    external_id, user_id, object_type, aspect_type, object_id, raw_payload
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (external_id) DO UPDATE SET
    external_id = EXCLUDED.external_id
RETURNING id, external_id, user_id, object_type, aspect_type, object_id, received_at, processed_at, raw_payload
`

type EnqueueActivityEventParams struct {
	ExternalID string      `json:"external_id"`
	UserID     pgtype.UUID `json:"user_id"`
	ObjectType string      `json:"object_type"`
	AspectType string      `json:"aspect_type"`
	ObjectID   int64       `json:"object_id"`
	RawPayload []byte      `json:"raw_payload"`
}

// Encola un evento de Strava (webhook). Devuelve la fila; si external_id
// ya existe, devuelve la fila previa sin error (idempotencia). Los callers
// pueden distinguir "nuevo" vs "ya visto" comparando received_at, o vía
// INSERT ... ON CONFLICT DO NOTHING RETURNING (cuando lo necesitemos).
func (q *Queries) EnqueueActivityEvent(ctx context.Context, arg EnqueueActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, enqueueActivityEvent,
		arg.ExternalID,
		arg.UserID,
		arg.ObjectType,
		arg.AspectType,
		arg.ObjectID,
		arg.RawPayload,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.UserID,
		&i.ObjectType,
		&i.AspectType,
		&i.ObjectID,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.RawPayload,
	)
	return i, err
}

const listPendingActivityEvents = `-- name: ListPendingActivityEvents :many
SELECT id, external_id, user_id, object_type, aspect_type, object_id, received_at, processed_at, raw_payload
FROM activity_events
WHERE processed_at IS NULL
ORDER BY received_at
LIMIT $1
`

// Lista los eventos pendientes (processed_at IS NULL) para alimentar un
// job de procesamiento. LIMIT defensivo para evitar scans descontrolados.
func (q *Queries) ListPendingActivityEvents(ctx context.Context, limit int32) ([]ActivityEvent, error) {
	rows, err := q.db.Query(ctx, listPendingActivityEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityEvent
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.UserID,
			&i.ObjectType,
			&i.AspectType,
			&i.ObjectID,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.RawPayload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActivityEventProcessed = `-- name: MarkActivityEventProcessed :exec
UPDATE activity_events
SET processed_at = now()
WHERE id = $1
`

// Marca un evento como procesado una vez consumido por el job.
func (q *Queries) MarkActivityEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markActivityEventProcessed, id)
	return err
}
