// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities_ext.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const firstActivityForUser = `-- name: FirstActivityForUser :one
SELECT MIN(started_at)::timestamptz AS first_started_at
FROM activities
WHERE user_id = $1
`

// Fecha de la primera actividad del usuario. RecalcTrainingLoad la usa
// cuando dashboard_metadata.last_recalc_at es NULL para acotar la
// ventana inicial del recálculo.
func (q *Queries) FirstActivityForUser(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, firstActivityForUser, userID)
	var first_started_at pgtype.Timestamptz
	err := row.Scan(&first_started_at)
	return first_started_at, err
}

const listActivitiesInRange = `-- name: ListActivitiesInRange :many
SELECT id,
       user_id,
       sport_type,
       started_at,
       elapsed_seconds,
       moving_seconds,
       distance_meters,
       elevation_gain_m,
       avg_hr,
       avg_power
FROM activities
WHERE user_id = $1
  AND started_at >= $2
  AND started_at <= $3
ORDER BY started_at ASC
`

type ListActivitiesInRangeParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type ListActivitiesInRangeRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	SportType      string             `json:"sport_type"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ElapsedSeconds int32              `json:"elapsed_seconds"`
	MovingSeconds  int32              `json:"moving_seconds"`
	DistanceMeters pgtype.Numeric     `json:"distance_meters"`
	ElevationGainM pgtype.Numeric     `json:"elevation_gain_m"`
	AvgHr          pgtype.Int2        `json:"avg_hr"`
	AvgPower       pgtype.Int2        `json:"avg_power"`
}

// Actividades de un usuario en un rango temporal, ordenadas ascendente.
// Solo columnas necesarias para ComputeDailyLoad: cada actividad se
// convierte en una entrada de TSS diario. Mantener la proyección
// estrecha evita cargar JSONB en el worker de recálculo.
func (q *Queries) ListActivitiesInRange(ctx context.Context, arg ListActivitiesInRangeParams) ([]ListActivitiesInRangeRow, error) {
	rows, err := q.db.Query(ctx, listActivitiesInRange, arg.UserID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitiesInRangeRow
	for rows.Next() {
		var i ListActivitiesInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SportType,
			&i.StartedAt,
			&i.ElapsedSeconds,
			&i.MovingSeconds,
			&i.DistanceMeters,
			&i.ElevationGainM,
			&i.AvgHr,
			&i.AvgPower,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
