// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActivityByExternalID = `-- name: GetActivityByExternalID :one
SELECT id, user_id, external_source, external_id, name, sport_type, started_at, elapsed_seconds, moving_seconds, distance_meters, elevation_gain_m, avg_hr, max_hr, avg_power, raw_payload, created_at, updated_at
FROM activities
WHERE user_id = $1
  AND external_source = $2
  AND external_id = $3
LIMIT 1
`

type GetActivityByExternalIDParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	ExternalSource string      `json:"external_source"`
	ExternalID     int64       `json:"external_id"`
}

// Búsqueda idempotente por (usuario, fuente, id externo). Es la operación
// central de la deduplicación: si existe, se actualiza; si no, se inserta.
func (q *Queries) GetActivityByExternalID(ctx context.Context, arg GetActivityByExternalIDParams) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivityByExternalID, arg.UserID, arg.ExternalSource, arg.ExternalID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalSource,
		&i.ExternalID,
		&i.Name,
		&i.SportType,
		&i.StartedAt,
		&i.ElapsedSeconds,
		&i.MovingSeconds,
		&i.DistanceMeters,
		&i.ElevationGainM,
		&i.AvgHr,
		&i.MaxHr,
		&i.AvgPower,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivitiesByUser = `-- name: ListActivitiesByUser :many
SELECT id, user_id, external_source, external_id, name, sport_type, started_at, elapsed_seconds, moving_seconds, distance_meters, elevation_gain_m, avg_hr, max_hr, avg_power, raw_payload, created_at, updated_at
FROM activities
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListActivitiesByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Lista paginada de actividades del usuario, ordenadas de más reciente a
// más antigua. El LIMIT es por la query (no cursor) porque el uso esperado
// es UI paginada con offset; cuando se necesite cursor, se añadirá en su
// propia query sin tocar esta.
func (q *Queries) ListActivitiesByUser(ctx context.Context, arg ListActivitiesByUserParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listActivitiesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExternalSource,
			&i.ExternalID,
			&i.Name,
			&i.SportType,
			&i.StartedAt,
			&i.ElapsedSeconds,
			&i.MovingSeconds,
			&i.DistanceMeters,
			&i.ElevationGainM,
			&i.AvgHr,
			&i.MaxHr,
			&i.AvgPower,
			&i.RawPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActivity = `-- name: UpsertActivity :one
INSERT INTO activities (
    user_id, external_source, external_id, name, sport_type,
    started_at, elapsed_seconds, moving_seconds,
    distance_meters, elevation_gain_m,
    avg_hr, max_hr, avg_power,
    raw_payload, updated_at
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10,
    $11, $12, $13,
    $14, now()
)
ON CONFLICT (user_id, external_source, external_id) DO UPDATE SET
    name            = EXCLUDED.name,
    sport_type      = EXCLUDED.sport_type,
    started_at      = EXCLUDED.started_at,
    elapsed_seconds = EXCLUDED.elapsed_seconds,
    moving_seconds  = EXCLUDED.moving_seconds,
    distance_meters = EXCLUDED.distance_meters,
    elevation_gain_m = EXCLUDED.elevation_gain_m,
    avg_hr          = EXCLUDED.avg_hr,
    max_hr          = EXCLUDED.max_hr,
    avg_power       = EXCLUDED.avg_power,
    raw_payload     = EXCLUDED.raw_payload,
    updated_at      = now()
RETURNING id, user_id, external_source, external_id, name, sport_type, started_at, elapsed_seconds, moving_seconds, distance_meters, elevation_gain_m, avg_hr, max_hr, avg_power, raw_payload, created_at, updated_at
`

type UpsertActivityParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	ExternalSource string             `json:"external_source"`
	ExternalID     int64              `json:"external_id"`
	Name           string             `json:"name"`
	SportType      string             `json:"sport_type"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ElapsedSeconds int32              `json:"elapsed_seconds"`
	MovingSeconds  int32              `json:"moving_seconds"`
	DistanceMeters pgtype.Numeric     `json:"distance_meters"`
	ElevationGainM pgtype.Numeric     `json:"elevation_gain_m"`
	AvgHr          pgtype.Int2        `json:"avg_hr"`
	MaxHr          pgtype.Int2        `json:"max_hr"`
	AvgPower       pgtype.Int2        `json:"avg_power"`
	RawPayload     []byte             `json:"raw_payload"`
}

// Inserción idempotente de actividad normalizada. Devuelve la fila final
// (insertada o actualizada) junto con xmax=0 → insert, xmax<>0 → update,
// expuesto vía RETURNING para que el caller distinga el caso.
func (q *Queries) UpsertActivity(ctx context.Context, arg UpsertActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, upsertActivity,
		arg.UserID,
		arg.ExternalSource,
		arg.ExternalID,
		arg.Name,
		arg.SportType,
		arg.StartedAt,
		arg.ElapsedSeconds,
		arg.MovingSeconds,
		arg.DistanceMeters,
		arg.ElevationGainM,
		arg.AvgHr,
		arg.MaxHr,
		arg.AvgPower,
		arg.RawPayload,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalSource,
		&i.ExternalID,
		&i.Name,
		&i.SportType,
		&i.StartedAt,
		&i.ElapsedSeconds,
		&i.MovingSeconds,
		&i.DistanceMeters,
		&i.ElevationGainM,
		&i.AvgHr,
		&i.MaxHr,
		&i.AvgPower,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertActivityStream = `-- name: UpsertActivityStream :one
INSERT INTO activity_streams (activity_id, stream_type, data)
VALUES ($1, $2, $3)
ON CONFLICT (activity_id, stream_type) DO UPDATE SET
    data = EXCLUDED.data
RETURNING activity_id, stream_type, data
`

type UpsertActivityStreamParams struct {
	ActivityID pgtype.UUID `json:"activity_id"`
	StreamType string      `json:"stream_type"`
	Data       []byte      `json:"data"`
}

// Guarda/actualiza un stream concreto de una actividad (HR, watts, ...).
// PRIMARY KEY (activity_id, stream_type) hace el upsert natural.
func (q *Queries) UpsertActivityStream(ctx context.Context, arg UpsertActivityStreamParams) (ActivityStream, error) {
	row := q.db.QueryRow(ctx, upsertActivityStream, arg.ActivityID, arg.StreamType, arg.Data)
	var i ActivityStream
	err := row.Scan(&i.ActivityID, &i.StreamType, &i.Data)
	return i, err
}
