// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard_metadata.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardMetadata = `-- name: GetDashboardMetadata :one
SELECT user_id, last_recalc_at, last_recalc_status, last_recalc_error, training_load_rows, updated_at
FROM dashboard_metadata
WHERE user_id = $1
`

// Lee la fila de metadata del usuario. Si nunca se ejecutó un recalc,
// la fila no existe; el handler /healthz extendido debe distinguir "sin
// metadata" (status=`never`) de "último recalc falló" (status=`error`).
func (q *Queries) GetDashboardMetadata(ctx context.Context, userID pgtype.UUID) (DashboardMetadatum, error) {
	row := q.db.QueryRow(ctx, getDashboardMetadata, userID)
	var i DashboardMetadatum
	err := row.Scan(
		&i.UserID,
		&i.LastRecalcAt,
		&i.LastRecalcStatus,
		&i.LastRecalcError,
		&i.TrainingLoadRows,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDashboardMetadata = `-- name: UpsertDashboardMetadata :one
INSERT INTO dashboard_metadata (
    user_id, last_recalc_at, last_recalc_status, last_recalc_error,
    training_load_rows, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    last_recalc_at     = EXCLUDED.last_recalc_at,
    last_recalc_status = EXCLUDED.last_recalc_status,
    last_recalc_error  = EXCLUDED.last_recalc_error,
    training_load_rows = EXCLUDED.training_load_rows,
    updated_at         = EXCLUDED.updated_at
RETURNING user_id, last_recalc_at, last_recalc_status, last_recalc_error, training_load_rows, updated_at
`

type UpsertDashboardMetadataParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	LastRecalcAt     pgtype.Timestamptz `json:"last_recalc_at"`
	LastRecalcStatus pgtype.Text        `json:"last_recalc_status"`
	LastRecalcError  pgtype.Text        `json:"last_recalc_error"`
	TrainingLoadRows int32              `json:"training_load_rows"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Inserta o actualiza la fila completa. El campo `training_load_rows`
// lo mantiene el caller (lo cuenta antes o lo deja en su valor previo).
func (q *Queries) UpsertDashboardMetadata(ctx context.Context, arg UpsertDashboardMetadataParams) (DashboardMetadatum, error) {
	row := q.db.QueryRow(ctx, upsertDashboardMetadata,
		arg.UserID,
		arg.LastRecalcAt,
		arg.LastRecalcStatus,
		arg.LastRecalcError,
		arg.TrainingLoadRows,
		arg.UpdatedAt,
	)
	var i DashboardMetadatum
	err := row.Scan(
		&i.UserID,
		&i.LastRecalcAt,
		&i.LastRecalcStatus,
		&i.LastRecalcError,
		&i.TrainingLoadRows,
		&i.UpdatedAt,
	)
	return i, err
}
