// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gpx_muros.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGPXMuro = `-- name: CreateGPXMuro :one
INSERT INTO gpx_muros (track_id, start_idx, end_idx, gain_m, distance_m, avg_slope_pct)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING track_id, start_idx, end_idx, gain_m, distance_m, avg_slope_pct
`

type CreateGPXMuroParams struct {
	TrackID     pgtype.UUID    `json:"track_id"`
	StartIdx    int32          `json:"start_idx"`
	EndIdx      int32          `json:"end_idx"`
	GainM       pgtype.Numeric `json:"gain_m"`
	DistanceM   pgtype.Numeric `json:"distance_m"`
	AvgSlopePct pgtype.Numeric `json:"avg_slope_pct"`
}

func (q *Queries) CreateGPXMuro(ctx context.Context, arg CreateGPXMuroParams) (GpxMuro, error) {
	row := q.db.QueryRow(ctx, createGPXMuro,
		arg.TrackID,
		arg.StartIdx,
		arg.EndIdx,
		arg.GainM,
		arg.DistanceM,
		arg.AvgSlopePct,
	)
	var i GpxMuro
	err := row.Scan(
		&i.TrackID,
		&i.StartIdx,
		&i.EndIdx,
		&i.GainM,
		&i.DistanceM,
		&i.AvgSlopePct,
	)
	return i, err
}

const listGPXMurosByTrack = `-- name: ListGPXMurosByTrack :many
SELECT track_id, start_idx, end_idx, gain_m, distance_m, avg_slope_pct FROM gpx_muros WHERE track_id = $1 ORDER BY start_idx
`

func (q *Queries) ListGPXMurosByTrack(ctx context.Context, trackID pgtype.UUID) ([]GpxMuro, error) {
	rows, err := q.db.Query(ctx, listGPXMurosByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GpxMuro
	for rows.Next() {
		var i GpxMuro
		if err := rows.Scan(
			&i.TrackID,
			&i.StartIdx,
			&i.EndIdx,
			&i.GainM,
			&i.DistanceM,
			&i.AvgSlopePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
