// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gpx_risk_zones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGPXRiskZone = `-- name: CreateGPXRiskZone :one
INSERT INTO gpx_risk_zones (
    track_id, start_idx, end_idx, risk_type, severity
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, track_id, start_idx, end_idx, risk_type, severity
`

type CreateGPXRiskZoneParams struct {
	TrackID  pgtype.UUID `json:"track_id"`
	StartIdx int32       `json:"start_idx"`
	EndIdx   int32       `json:"end_idx"`
	RiskType string      `json:"risk_type"`
	Severity string      `json:"severity"`
}

func (q *Queries) CreateGPXRiskZone(ctx context.Context, arg CreateGPXRiskZoneParams) (GpxRiskZone, error) {
	row := q.db.QueryRow(ctx, createGPXRiskZone,
		arg.TrackID,
		arg.StartIdx,
		arg.EndIdx,
		arg.RiskType,
		arg.Severity,
	)
	var i GpxRiskZone
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.StartIdx,
		&i.EndIdx,
		&i.RiskType,
		&i.Severity,
	)
	return i, err
}

const listGPXRiskZonesByTrack = `-- name: ListGPXRiskZonesByTrack :many
SELECT id, track_id, start_idx, end_idx, risk_type, severity FROM gpx_risk_zones WHERE track_id = $1 ORDER BY start_idx
`

func (q *Queries) ListGPXRiskZonesByTrack(ctx context.Context, trackID pgtype.UUID) ([]GpxRiskZone, error) {
	rows, err := q.db.Query(ctx, listGPXRiskZonesByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GpxRiskZone
	for rows.Next() {
		var i GpxRiskZone
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.StartIdx,
			&i.EndIdx,
			&i.RiskType,
			&i.Severity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
