// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gpx_climbs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGPXClimb = `-- name: CreateGPXClimb :one
INSERT INTO gpx_climbs (
    track_id, is_king_climb, start_idx, end_idx, gain_m, distance_m, avg_slope_pct
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, track_id, is_king_climb, start_idx, end_idx, gain_m, distance_m, avg_slope_pct
`

type CreateGPXClimbParams struct {
	TrackID     pgtype.UUID    `json:"track_id"`
	IsKingClimb bool           `json:"is_king_climb"`
	StartIdx    int32          `json:"start_idx"`
	EndIdx      int32          `json:"end_idx"`
	GainM       pgtype.Numeric `json:"gain_m"`
	DistanceM   pgtype.Numeric `json:"distance_m"`
	AvgSlopePct pgtype.Numeric `json:"avg_slope_pct"`
}

func (q *Queries) CreateGPXClimb(ctx context.Context, arg CreateGPXClimbParams) (GpxClimb, error) {
	row := q.db.QueryRow(ctx, createGPXClimb,
		arg.TrackID,
		arg.IsKingClimb,
		arg.StartIdx,
		arg.EndIdx,
		arg.GainM,
		arg.DistanceM,
		arg.AvgSlopePct,
	)
	var i GpxClimb
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.IsKingClimb,
		&i.StartIdx,
		&i.EndIdx,
		&i.GainM,
		&i.DistanceM,
		&i.AvgSlopePct,
	)
	return i, err
}

const listGPXClimbsByTrack = `-- name: ListGPXClimbsByTrack :many
SELECT id, track_id, is_king_climb, start_idx, end_idx, gain_m, distance_m, avg_slope_pct FROM gpx_climbs WHERE track_id = $1 ORDER BY start_idx
`

func (q *Queries) ListGPXClimbsByTrack(ctx context.Context, trackID pgtype.UUID) ([]GpxClimb, error) {
	rows, err := q.db.Query(ctx, listGPXClimbsByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GpxClimb
	for rows.Next() {
		var i GpxClimb
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.IsKingClimb,
			&i.StartIdx,
			&i.EndIdx,
			&i.GainM,
			&i.DistanceM,
			&i.AvgSlopePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
