// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gpx_tracks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGPXTrack = `-- name: CreateGPXTrack :one
INSERT INTO gpx_tracks (
    user_id, name, file_hash, file_size_bytes, coordinates,
    distance_m, moving_time_s, d_plus_m, d_minus_m,
    max_elevation_m, min_elevation_m, avg_slope_pct, max_slope_pct,
    effort_index, itra_points, leg_breaker_index, estimated_vam,
    difficulty_score, difficulty_label, runnability_pct,
    king_climb, track_type, direction
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20,
    $21, $22, $23
)
RETURNING id, user_id, name, file_hash, file_size_bytes, coordinates, distance_m, moving_time_s, d_plus_m, d_minus_m, max_elevation_m, min_elevation_m, avg_slope_pct, max_slope_pct, effort_index, itra_points, leg_breaker_index, estimated_vam, difficulty_score, difficulty_label, runnability_pct, king_climb, track_type, direction, created_at, analyzed_at, updated_at
`

type CreateGPXTrackParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	Name            string         `json:"name"`
	FileHash        string         `json:"file_hash"`
	FileSizeBytes   int64          `json:"file_size_bytes"`
	Coordinates     []byte         `json:"coordinates"`
	DistanceM       pgtype.Numeric `json:"distance_m"`
	MovingTimeS     int32          `json:"moving_time_s"`
	DPlusM          pgtype.Numeric `json:"d_plus_m"`
	DMinusM         pgtype.Numeric `json:"d_minus_m"`
	MaxElevationM   pgtype.Numeric `json:"max_elevation_m"`
	MinElevationM   pgtype.Numeric `json:"min_elevation_m"`
	AvgSlopePct     pgtype.Numeric `json:"avg_slope_pct"`
	MaxSlopePct     pgtype.Numeric `json:"max_slope_pct"`
	EffortIndex     pgtype.Numeric `json:"effort_index"`
	ItraPoints      pgtype.Numeric `json:"itra_points"`
	LegBreakerIndex pgtype.Numeric `json:"leg_breaker_index"`
	EstimatedVam    pgtype.Numeric `json:"estimated_vam"`
	DifficultyScore int32          `json:"difficulty_score"`
	DifficultyLabel string         `json:"difficulty_label"`
	RunnabilityPct  pgtype.Numeric `json:"runnability_pct"`
	KingClimb       []byte         `json:"king_climb"`
	TrackType       string         `json:"track_type"`
	Direction       pgtype.Text    `json:"direction"`
}

func (q *Queries) CreateGPXTrack(ctx context.Context, arg CreateGPXTrackParams) (GpxTrack, error) {
	row := q.db.QueryRow(ctx, createGPXTrack,
		arg.UserID,
		arg.Name,
		arg.FileHash,
		arg.FileSizeBytes,
		arg.Coordinates,
		arg.DistanceM,
		arg.MovingTimeS,
		arg.DPlusM,
		arg.DMinusM,
		arg.MaxElevationM,
		arg.MinElevationM,
		arg.AvgSlopePct,
		arg.MaxSlopePct,
		arg.EffortIndex,
		arg.ItraPoints,
		arg.LegBreakerIndex,
		arg.EstimatedVam,
		arg.DifficultyScore,
		arg.DifficultyLabel,
		arg.RunnabilityPct,
		arg.KingClimb,
		arg.TrackType,
		arg.Direction,
	)
	var i GpxTrack
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.FileHash,
		&i.FileSizeBytes,
		&i.Coordinates,
		&i.DistanceM,
		&i.MovingTimeS,
		&i.DPlusM,
		&i.DMinusM,
		&i.MaxElevationM,
		&i.MinElevationM,
		&i.AvgSlopePct,
		&i.MaxSlopePct,
		&i.EffortIndex,
		&i.ItraPoints,
		&i.LegBreakerIndex,
		&i.EstimatedVam,
		&i.DifficultyScore,
		&i.DifficultyLabel,
		&i.RunnabilityPct,
		&i.KingClimb,
		&i.TrackType,
		&i.Direction,
		&i.CreatedAt,
		&i.AnalyzedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGPXTrack = `-- name: DeleteGPXTrack :exec
DELETE FROM gpx_tracks
WHERE id = $1 AND user_id = $2
`

type DeleteGPXTrackParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteGPXTrack(ctx context.Context, arg DeleteGPXTrackParams) error {
	_, err := q.db.Exec(ctx, deleteGPXTrack, arg.ID, arg.UserID)
	return err
}

const getGPXTrackByHash = `-- name: GetGPXTrackByHash :one
SELECT id, user_id, name, file_hash, file_size_bytes, coordinates, distance_m, moving_time_s, d_plus_m, d_minus_m, max_elevation_m, min_elevation_m, avg_slope_pct, max_slope_pct, effort_index, itra_points, leg_breaker_index, estimated_vam, difficulty_score, difficulty_label, runnability_pct, king_climb, track_type, direction, created_at, analyzed_at, updated_at
FROM gpx_tracks
WHERE user_id = $1 AND file_hash = $2
LIMIT 1
`

type GetGPXTrackByHashParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FileHash string      `json:"file_hash"`
}

func (q *Queries) GetGPXTrackByHash(ctx context.Context, arg GetGPXTrackByHashParams) (GpxTrack, error) {
	row := q.db.QueryRow(ctx, getGPXTrackByHash, arg.UserID, arg.FileHash)
	var i GpxTrack
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.FileHash,
		&i.FileSizeBytes,
		&i.Coordinates,
		&i.DistanceM,
		&i.MovingTimeS,
		&i.DPlusM,
		&i.DMinusM,
		&i.MaxElevationM,
		&i.MinElevationM,
		&i.AvgSlopePct,
		&i.MaxSlopePct,
		&i.EffortIndex,
		&i.ItraPoints,
		&i.LegBreakerIndex,
		&i.EstimatedVam,
		&i.DifficultyScore,
		&i.DifficultyLabel,
		&i.RunnabilityPct,
		&i.KingClimb,
		&i.TrackType,
		&i.Direction,
		&i.CreatedAt,
		&i.AnalyzedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGPXTrackByID = `-- name: GetGPXTrackByID :one
SELECT id, user_id, name, file_hash, file_size_bytes, coordinates, distance_m, moving_time_s, d_plus_m, d_minus_m, max_elevation_m, min_elevation_m, avg_slope_pct, max_slope_pct, effort_index, itra_points, leg_breaker_index, estimated_vam, difficulty_score, difficulty_label, runnability_pct, king_climb, track_type, direction, created_at, analyzed_at, updated_at
FROM gpx_tracks
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetGPXTrackByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGPXTrackByID(ctx context.Context, arg GetGPXTrackByIDParams) (GpxTrack, error) {
	row := q.db.QueryRow(ctx, getGPXTrackByID, arg.ID, arg.UserID)
	var i GpxTrack
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.FileHash,
		&i.FileSizeBytes,
		&i.Coordinates,
		&i.DistanceM,
		&i.MovingTimeS,
		&i.DPlusM,
		&i.DMinusM,
		&i.MaxElevationM,
		&i.MinElevationM,
		&i.AvgSlopePct,
		&i.MaxSlopePct,
		&i.EffortIndex,
		&i.ItraPoints,
		&i.LegBreakerIndex,
		&i.EstimatedVam,
		&i.DifficultyScore,
		&i.DifficultyLabel,
		&i.RunnabilityPct,
		&i.KingClimb,
		&i.TrackType,
		&i.Direction,
		&i.CreatedAt,
		&i.AnalyzedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGPXTracksByUser = `-- name: ListGPXTracksByUser :many
SELECT id, user_id, name, file_hash, file_size_bytes, coordinates, distance_m, moving_time_s, d_plus_m, d_minus_m, max_elevation_m, min_elevation_m, avg_slope_pct, max_slope_pct, effort_index, itra_points, leg_breaker_index, estimated_vam, difficulty_score, difficulty_label, runnability_pct, king_climb, track_type, direction, created_at, analyzed_at, updated_at
FROM gpx_tracks
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListGPXTracksByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListGPXTracksByUser(ctx context.Context, arg ListGPXTracksByUserParams) ([]GpxTrack, error) {
	rows, err := q.db.Query(ctx, listGPXTracksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GpxTrack
	for rows.Next() {
		var i GpxTrack
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.FileHash,
			&i.FileSizeBytes,
			&i.Coordinates,
			&i.DistanceM,
			&i.MovingTimeS,
			&i.DPlusM,
			&i.DMinusM,
			&i.MaxElevationM,
			&i.MinElevationM,
			&i.AvgSlopePct,
			&i.MaxSlopePct,
			&i.EffortIndex,
			&i.ItraPoints,
			&i.LegBreakerIndex,
			&i.EstimatedVam,
			&i.DifficultyScore,
			&i.DifficultyLabel,
			&i.RunnabilityPct,
			&i.KingClimb,
			&i.TrackType,
			&i.Direction,
			&i.CreatedAt,
			&i.AnalyzedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
