// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gpx_recovery_zones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGPXRecoveryZone = `-- name: CreateGPXRecoveryZone :one
INSERT INTO gpx_recovery_zones (track_id, start_idx, end_idx, distance_m)
VALUES ($1, $2, $3, $4)
RETURNING track_id, start_idx, end_idx, distance_m
`

type CreateGPXRecoveryZoneParams struct {
	TrackID   pgtype.UUID    `json:"track_id"`
	StartIdx  int32          `json:"start_idx"`
	EndIdx    int32          `json:"end_idx"`
	DistanceM pgtype.Numeric `json:"distance_m"`
}

func (q *Queries) CreateGPXRecoveryZone(ctx context.Context, arg CreateGPXRecoveryZoneParams) (GpxRecoveryZone, error) {
	row := q.db.QueryRow(ctx, createGPXRecoveryZone,
		arg.TrackID,
		arg.StartIdx,
		arg.EndIdx,
		arg.DistanceM,
	)
	var i GpxRecoveryZone
	err := row.Scan(
		&i.TrackID,
		&i.StartIdx,
		&i.EndIdx,
		&i.DistanceM,
	)
	return i, err
}

const listGPXRecoveryZonesByTrack = `-- name: ListGPXRecoveryZonesByTrack :many
SELECT track_id, start_idx, end_idx, distance_m FROM gpx_recovery_zones WHERE track_id = $1 ORDER BY start_idx
`

func (q *Queries) ListGPXRecoveryZonesByTrack(ctx context.Context, trackID pgtype.UUID) ([]GpxRecoveryZone, error) {
	rows, err := q.db.Query(ctx, listGPXRecoveryZonesByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GpxRecoveryZone
	for rows.Next() {
		var i GpxRecoveryZone
		if err := rows.Scan(
			&i.TrackID,
			&i.StartIdx,
			&i.EndIdx,
			&i.DistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
