// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gpx_km_vertical.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGPXKmVerticalByTrack = `-- name: GetGPXKmVerticalByTrack :one
SELECT track_id, start_idx, end_idx, gain_m, distance_m FROM gpx_km_vertical WHERE track_id = $1
`

func (q *Queries) GetGPXKmVerticalByTrack(ctx context.Context, trackID pgtype.UUID) (GpxKmVertical, error) {
	row := q.db.QueryRow(ctx, getGPXKmVerticalByTrack, trackID)
	var i GpxKmVertical
	err := row.Scan(
		&i.TrackID,
		&i.StartIdx,
		&i.EndIdx,
		&i.GainM,
		&i.DistanceM,
	)
	return i, err
}

const upsertGPXKmVertical = `-- name: UpsertGPXKmVertical :one
INSERT INTO gpx_km_vertical (track_id, start_idx, end_idx, gain_m, distance_m)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (track_id) DO UPDATE SET
    start_idx = EXCLUDED.start_idx,
    end_idx = EXCLUDED.end_idx,
    gain_m = EXCLUDED.gain_m,
    distance_m = EXCLUDED.distance_m
RETURNING track_id, start_idx, end_idx, gain_m, distance_m
`

type UpsertGPXKmVerticalParams struct {
	TrackID   pgtype.UUID    `json:"track_id"`
	StartIdx  int32          `json:"start_idx"`
	EndIdx    int32          `json:"end_idx"`
	GainM     pgtype.Numeric `json:"gain_m"`
	DistanceM pgtype.Numeric `json:"distance_m"`
}

func (q *Queries) UpsertGPXKmVertical(ctx context.Context, arg UpsertGPXKmVerticalParams) (GpxKmVertical, error) {
	row := q.db.QueryRow(ctx, upsertGPXKmVertical,
		arg.TrackID,
		arg.StartIdx,
		arg.EndIdx,
		arg.GainM,
		arg.DistanceM,
	)
	var i GpxKmVertical
	err := row.Scan(
		&i.TrackID,
		&i.StartIdx,
		&i.EndIdx,
		&i.GainM,
		&i.DistanceM,
	)
	return i, err
}
