// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_zones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHRZonesByActivity = `-- name: GetHRZonesByActivity :one
SELECT activity_id, z1_seconds, z2_seconds, z3_seconds, z4_seconds, z5_seconds, computed_at FROM hr_zones WHERE activity_id = $1 LIMIT 1
`

func (q *Queries) GetHRZonesByActivity(ctx context.Context, activityID pgtype.UUID) (HrZone, error) {
	row := q.db.QueryRow(ctx, getHRZonesByActivity, activityID)
	var i HrZone
	err := row.Scan(
		&i.ActivityID,
		&i.Z1Seconds,
		&i.Z2Seconds,
		&i.Z3Seconds,
		&i.Z4Seconds,
		&i.Z5Seconds,
		&i.ComputedAt,
	)
	return i, err
}

const upsertHRZones = `-- name: UpsertHRZones :one
INSERT INTO hr_zones (activity_id, z1_seconds, z2_seconds, z3_seconds, z4_seconds, z5_seconds, computed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (activity_id) DO UPDATE SET
    z1_seconds  = EXCLUDED.z1_seconds,
    z2_seconds  = EXCLUDED.z2_seconds,
    z3_seconds  = EXCLUDED.z3_seconds,
    z4_seconds  = EXCLUDED.z4_seconds,
    z5_seconds  = EXCLUDED.z5_seconds,
    computed_at = EXCLUDED.computed_at
RETURNING activity_id, z1_seconds, z2_seconds, z3_seconds, z4_seconds, z5_seconds, computed_at
`

type UpsertHRZonesParams struct {
	ActivityID pgtype.UUID        `json:"activity_id"`
	Z1Seconds  int32              `json:"z1_seconds"`
	Z2Seconds  int32              `json:"z2_seconds"`
	Z3Seconds  int32              `json:"z3_seconds"`
	Z4Seconds  int32              `json:"z4_seconds"`
	Z5Seconds  int32              `json:"z5_seconds"`
	ComputedAt pgtype.Timestamptz `json:"computed_at"`
}

// Idempotente por PK activity_id. Upsert de zonas HR calculadas.
func (q *Queries) UpsertHRZones(ctx context.Context, arg UpsertHRZonesParams) (HrZone, error) {
	row := q.db.QueryRow(ctx, upsertHRZones,
		arg.ActivityID,
		arg.Z1Seconds,
		arg.Z2Seconds,
		arg.Z3Seconds,
		arg.Z4Seconds,
		arg.Z5Seconds,
		arg.ComputedAt,
	)
	var i HrZone
	err := row.Scan(
		&i.ActivityID,
		&i.Z1Seconds,
		&i.Z2Seconds,
		&i.Z3Seconds,
		&i.Z4Seconds,
		&i.Z5Seconds,
		&i.ComputedAt,
	)
	return i, err
}
