// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hr_zones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHRZonesByActivity = `-- name: GetHRZonesByActivity :one
SELECT activity_id, z1_seconds, z2_seconds, z3_seconds, z4_seconds, z5_seconds, computed_at FROM hr_zones WHERE activity_id = $1 LIMIT 1
`

func (q *Queries) GetHRZonesByActivity(ctx context.Context, activityID pgtype.UUID) (HrZone, error) {
	row := q.db.QueryRow(ctx, getHRZonesByActivity, activityID)
	var i HrZone
	err := row.Scan(
		&i.ActivityID,
		&i.Z1Seconds,
		&i.Z2Seconds,
		&i.Z3Seconds,
		&i.Z4Seconds,
		&i.Z5Seconds,
		&i.ComputedAt,
	)
	return i, err
}

const sumActivitiesDurationInRange = `-- name: SumActivitiesDurationInRange :one
SELECT COUNT(*)::bigint                                       AS activities_total,
       COALESCE(SUM(elapsed_seconds), 0)::bigint             AS elapsed_seconds_total,
       COALESCE(SUM(elapsed_seconds) FILTER (WHERE avg_hr IS NOT NULL), 0)::bigint
                                                                              AS elapsed_seconds_with_avg_hr,
       COALESCE(COUNT(*) FILTER (WHERE avg_hr IS NOT NULL), 0)::bigint
                                                                              AS activities_with_avg_hr
FROM activities
WHERE user_id = $1
  AND started_at >= $2
  AND started_at <= $3
`

type SumActivitiesDurationInRangeParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type SumActivitiesDurationInRangeRow struct {
	ActivitiesTotal         int64 `json:"activities_total"`
	ElapsedSecondsTotal     int64 `json:"elapsed_seconds_total"`
	ElapsedSecondsWithAvgHr int64 `json:"elapsed_seconds_with_avg_hr"`
	ActivitiesWithAvgHr     int64 `json:"activities_with_avg_hr"`
}

// Suma `elapsed_seconds` y cuenta actividades del usuario en un rango
// (sin filtrar por `hr_zones`). DA-003 fallback: cuando no hay zonas
// precomputadas, repartimos `avg_hr × elapsed` por zonas usando
// `SumActivitiesDurationInRange` como denominador.
//
// Mantiene `activities_with_avg_hr` separado para no contar filas
// con `avg_hr = NULL` (que aportan 0 al cálculo y son ruido).
func (q *Queries) SumActivitiesDurationInRange(ctx context.Context, arg SumActivitiesDurationInRangeParams) (SumActivitiesDurationInRangeRow, error) {
	row := q.db.QueryRow(ctx, sumActivitiesDurationInRange, arg.UserID, arg.StartedAt, arg.StartedAt_2)
	var i SumActivitiesDurationInRangeRow
	err := row.Scan(
		&i.ActivitiesTotal,
		&i.ElapsedSecondsTotal,
		&i.ElapsedSecondsWithAvgHr,
		&i.ActivitiesWithAvgHr,
	)
	return i, err
}

const sumHRZonesInRange = `-- name: SumHRZonesInRange :one
SELECT COALESCE(SUM(z1_seconds), 0)::bigint  AS z1_seconds,
       COALESCE(SUM(z2_seconds), 0)::bigint  AS z2_seconds,
       COALESCE(SUM(z3_seconds), 0)::bigint  AS z3_seconds,
       COALESCE(SUM(z4_seconds), 0)::bigint  AS z4_seconds,
       COALESCE(SUM(z5_seconds), 0)::bigint  AS z5_seconds,
       COUNT(*)::bigint                      AS activities_with_zones
FROM hr_zones hz
JOIN activities a ON a.id = hz.activity_id
WHERE a.user_id = $1
  AND a.started_at >= $2
  AND a.started_at <= $3
`

type SumHRZonesInRangeParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	StartedAt_2 pgtype.Timestamptz `json:"started_at_2"`
}

type SumHRZonesInRangeRow struct {
	Z1Seconds           int64 `json:"z1_seconds"`
	Z2Seconds           int64 `json:"z2_seconds"`
	Z3Seconds           int64 `json:"z3_seconds"`
	Z4Seconds           int64 `json:"z4_seconds"`
	Z5Seconds           int64 `json:"z5_seconds"`
	ActivitiesWithZones int64 `json:"activities_with_zones"`
}

// Suma los segundos por zona HR sobre las actividades del usuario que
// tienen fila en `hr_zones` y cuyo `started_at` cae dentro del rango.
// Devuelve 0 cuando no hay filas (los handlers usan eso para distinguir
// "sin datos HR" → fallback a avg_hr × elapsed).
//
// PR3 DA-003 (issue #16): la fuente primaria es la tabla `hr_zones`
// precomputada por StravaStreams worker. La ruta "activity_streams
// heartrate JSONB" documentada en el spec se sustituye por `hr_zones`
// (decisión de usuario 2026-10-01) por simplicidad y porque ya está
// alineada con la arquitectura actual.
func (q *Queries) SumHRZonesInRange(ctx context.Context, arg SumHRZonesInRangeParams) (SumHRZonesInRangeRow, error) {
	row := q.db.QueryRow(ctx, sumHRZonesInRange, arg.UserID, arg.StartedAt, arg.StartedAt_2)
	var i SumHRZonesInRangeRow
	err := row.Scan(
		&i.Z1Seconds,
		&i.Z2Seconds,
		&i.Z3Seconds,
		&i.Z4Seconds,
		&i.Z5Seconds,
		&i.ActivitiesWithZones,
	)
	return i, err
}

const upsertHRZones = `-- name: UpsertHRZones :one
INSERT INTO hr_zones (activity_id, z1_seconds, z2_seconds, z3_seconds, z4_seconds, z5_seconds, computed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (activity_id) DO UPDATE SET
    z1_seconds  = EXCLUDED.z1_seconds,
    z2_seconds  = EXCLUDED.z2_seconds,
    z3_seconds  = EXCLUDED.z3_seconds,
    z4_seconds  = EXCLUDED.z4_seconds,
    z5_seconds  = EXCLUDED.z5_seconds,
    computed_at = EXCLUDED.computed_at
RETURNING activity_id, z1_seconds, z2_seconds, z3_seconds, z4_seconds, z5_seconds, computed_at
`

type UpsertHRZonesParams struct {
	ActivityID pgtype.UUID        `json:"activity_id"`
	Z1Seconds  int32              `json:"z1_seconds"`
	Z2Seconds  int32              `json:"z2_seconds"`
	Z3Seconds  int32              `json:"z3_seconds"`
	Z4Seconds  int32              `json:"z4_seconds"`
	Z5Seconds  int32              `json:"z5_seconds"`
	ComputedAt pgtype.Timestamptz `json:"computed_at"`
}

// Idempotente por PK activity_id. Upsert de zonas HR calculadas.
func (q *Queries) UpsertHRZones(ctx context.Context, arg UpsertHRZonesParams) (HrZone, error) {
	row := q.db.QueryRow(ctx, upsertHRZones,
		arg.ActivityID,
		arg.Z1Seconds,
		arg.Z2Seconds,
		arg.Z3Seconds,
		arg.Z4Seconds,
		arg.Z5Seconds,
		arg.ComputedAt,
	)
	var i HrZone
	err := row.Scan(
		&i.ActivityID,
		&i.Z1Seconds,
		&i.Z2Seconds,
		&i.Z3Seconds,
		&i.Z4Seconds,
		&i.Z5Seconds,
		&i.ComputedAt,
	)
	return i, err
}
