// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlc

import (
	"context"

	"github.com/fgjcarlos/ghamusinos/internal/db/status"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (email, token_hash, status, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, token_hash, status, expires_at, accepted_at, created_at
`

type CreateInviteParams struct {
	Email     string             `json:"email"`
	TokenHash string             `json:"-"`
	Status    status.Status      `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.Email,
		arg.TokenHash,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveInviteByEmail = `-- name: GetActiveInviteByEmail :one
SELECT id, email, status, expires_at, accepted_at, created_at
FROM invites
WHERE email     = $1
  AND status    IN ('pending', 'accepted')
  AND (expires_at IS NULL OR expires_at > now())
LIMIT 1
`

type GetActiveInviteByEmailRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	Status     status.Status      `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Devuelve la invitación vigente para un email dado.
// "Vigente" significa: status pending o accepted, y no expirada
// (expires_at es NULL o está en el futuro).
// Usado en el flujo de bloqueo por invitación (v1-phase-1-plan.md §4.7).
func (q *Queries) GetActiveInviteByEmail(ctx context.Context, email string) (GetActiveInviteByEmailRow, error) {
	row := q.db.QueryRow(ctx, getActiveInviteByEmail, email)
	var i GetActiveInviteByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, email, token_hash, status, expires_at, accepted_at, created_at
FROM invites
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE invites
SET
    status      = 'accepted',
    accepted_at = now()
WHERE id = $1
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, id)
	return err
}
