// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (email, token_hash, status, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, token_hash, status, expires_at, accepted_at, created_at
`

type CreateInviteParams struct {
	Email     string             `json:"email"`
	TokenHash string             `json:"token_hash"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.Email,
		arg.TokenHash,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, email, token_hash, status, expires_at, accepted_at, created_at
FROM invites
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markInviteAccepted = `-- name: MarkInviteAccepted :exec
UPDATE invites
SET
    status      = 'accepted',
    accepted_at = now()
WHERE id = $1
`

func (q *Queries) MarkInviteAccepted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markInviteAccepted, id)
	return err
}
