// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/fgjcarlos/ghamusinos/internal/db/status"
	"github.com/jackc/pgx/v5/pgtype"
)

type Invite struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	TokenHash  string             `json:"-"`
	Status     status.Status      `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID         `json:"id"`
	ClerkUserID  string              `json:"clerk_user_id"`
	Email        string              `json:"email"`
	DisplayName  pgtype.Text         `json:"display_name"`
	InviteStatus status.InviteStatus `json:"invite_status"`
	HrMax        pgtype.Int2         `json:"hr_max"`
	Lthr         pgtype.Int2         `json:"lthr"`
	Ftp          pgtype.Int2         `json:"ftp"`
	Level        pgtype.Text         `json:"level"`
	Timezone     string              `json:"timezone"`
	AiEnabled    bool                `json:"ai_enabled"`
	CreatedAt    pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `json:"updated_at"`
}
