// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Invite struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	TokenHash  string             `json:"token_hash"`
	Status     string             `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	ClerkUserID  string             `json:"clerk_user_id"`
	Email        string             `json:"email"`
	DisplayName  pgtype.Text        `json:"display_name"`
	InviteStatus string             `json:"invite_status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
