// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/fgjcarlos/ghamusinos/internal/db/status"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ExternalSource string             `json:"external_source"`
	ExternalID     int64              `json:"external_id"`
	Name           string             `json:"name"`
	SportType      string             `json:"sport_type"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ElapsedSeconds int32              `json:"elapsed_seconds"`
	MovingSeconds  int32              `json:"moving_seconds"`
	DistanceMeters pgtype.Numeric     `json:"distance_meters"`
	ElevationGainM pgtype.Numeric     `json:"elevation_gain_m"`
	AvgHr          pgtype.Int2        `json:"avg_hr"`
	MaxHr          pgtype.Int2        `json:"max_hr"`
	AvgPower       pgtype.Int2        `json:"avg_power"`
	RawPayload     []byte             `json:"raw_payload"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ActivityEvent struct {
	ID             pgtype.UUID        `json:"id"`
	ExternalID     string             `json:"external_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ObjectType     string             `json:"object_type"`
	AspectType     string             `json:"aspect_type"`
	ObjectID       int64              `json:"object_id"`
	OwnerID        pgtype.Int8        `json:"owner_id"`
	SubscriptionID pgtype.Int8        `json:"subscription_id"`
	EventTime      pgtype.Timestamptz `json:"event_time"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	RawPayload     []byte             `json:"raw_payload"`
}

type ActivityStream struct {
	ActivityID pgtype.UUID `json:"activity_id"`
	StreamType string      `json:"stream_type"`
	Data       []byte      `json:"data"`
}

type GpxClimb struct {
	ID          pgtype.UUID    `json:"id"`
	TrackID     pgtype.UUID    `json:"track_id"`
	IsKingClimb bool           `json:"is_king_climb"`
	StartIdx    int32          `json:"start_idx"`
	EndIdx      int32          `json:"end_idx"`
	GainM       pgtype.Numeric `json:"gain_m"`
	DistanceM   pgtype.Numeric `json:"distance_m"`
	AvgSlopePct pgtype.Numeric `json:"avg_slope_pct"`
}

type GpxRiskZone struct {
	ID       pgtype.UUID `json:"id"`
	TrackID  pgtype.UUID `json:"track_id"`
	StartIdx int32       `json:"start_idx"`
	EndIdx   int32       `json:"end_idx"`
	RiskType string      `json:"risk_type"`
	Severity string      `json:"severity"`
}

type GpxTrack struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Name            string             `json:"name"`
	FileHash        string             `json:"file_hash"`
	FileSizeBytes   int64              `json:"file_size_bytes"`
	Coordinates     []byte             `json:"coordinates"`
	DistanceM       pgtype.Numeric     `json:"distance_m"`
	MovingTimeS     int32              `json:"moving_time_s"`
	DPlusM          pgtype.Numeric     `json:"d_plus_m"`
	DMinusM         pgtype.Numeric     `json:"d_minus_m"`
	MaxElevationM   pgtype.Numeric     `json:"max_elevation_m"`
	MinElevationM   pgtype.Numeric     `json:"min_elevation_m"`
	AvgSlopePct     pgtype.Numeric     `json:"avg_slope_pct"`
	MaxSlopePct     pgtype.Numeric     `json:"max_slope_pct"`
	EffortIndex     pgtype.Numeric     `json:"effort_index"`
	ItraPoints      pgtype.Numeric     `json:"itra_points"`
	LegBreakerIndex pgtype.Numeric     `json:"leg_breaker_index"`
	EstimatedVam    pgtype.Numeric     `json:"estimated_vam"`
	DifficultyScore int32              `json:"difficulty_score"`
	DifficultyLabel string             `json:"difficulty_label"`
	RunnabilityPct  pgtype.Numeric     `json:"runnability_pct"`
	KingClimb       []byte             `json:"king_climb"`
	TrackType       string             `json:"track_type"`
	Direction       pgtype.Text        `json:"direction"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AnalyzedAt      pgtype.Timestamptz `json:"analyzed_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type HrZone struct {
	ActivityID pgtype.UUID        `json:"activity_id"`
	Z1Seconds  int32              `json:"z1_seconds"`
	Z2Seconds  int32              `json:"z2_seconds"`
	Z3Seconds  int32              `json:"z3_seconds"`
	Z4Seconds  int32              `json:"z4_seconds"`
	Z5Seconds  int32              `json:"z5_seconds"`
	ComputedAt pgtype.Timestamptz `json:"computed_at"`
}

type Invite struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	TokenHash  string             `json:"-"`
	Status     status.Status      `json:"status"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type StravaToken struct {
	UserID        pgtype.UUID        `json:"user_id"`
	AccessCipher  string             `json:"access_cipher"`
	RefreshCipher string             `json:"refresh_cipher"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	AthleteID     int64              `json:"athlete_id"`
	Scopes        string             `json:"scopes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SyncSession struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Status          string             `json:"status"`
	WindowDays      int32              `json:"window_days"`
	TotalActivities int32              `json:"total_activities"`
	Imported        int32              `json:"imported"`
	Skipped         int32              `json:"skipped"`
	Error           pgtype.Text        `json:"error"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
}

type User struct {
	ID           pgtype.UUID         `json:"id"`
	ClerkUserID  string              `json:"clerk_user_id"`
	Email        string              `json:"email"`
	DisplayName  pgtype.Text         `json:"display_name"`
	InviteStatus status.InviteStatus `json:"invite_status"`
	HrMax        pgtype.Int2         `json:"hr_max"`
	Lthr         pgtype.Int2         `json:"lthr"`
	Ftp          pgtype.Int2         `json:"ftp"`
	Level        pgtype.Text         `json:"level"`
	Timezone     string              `json:"timezone"`
	AiEnabled    bool                `json:"ai_enabled"`
	CreatedAt    pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz  `json:"updated_at"`
}
