// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateGPXClimb(ctx context.Context, arg CreateGPXClimbParams) (GpxClimb, error)
	CreateGPXRiskZone(ctx context.Context, arg CreateGPXRiskZoneParams) (GpxRiskZone, error)
	// Issue #171, A8: d_plus_m / d_minus_m admiten NULL cuando la cobertura
	// de elevación es insuficiente (ver migración 00010). elevation_coverage
	// (0..1) se persiste junto al track para que la API pueda avisar al
	// frontend. NULL d+/d- con elevation_coverage conocido es el contrato.
	CreateGPXTrack(ctx context.Context, arg CreateGPXTrackParams) (GpxTrack, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	// Crea una nueva sesión de sincronización en estado 'pending'. El caller la
	// transita a 'running' con UpdateSyncSessionStatus cuando empieza a procesar.
	CreateSyncSession(ctx context.Context, arg CreateSyncSessionParams) (SyncSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGPXTrack(ctx context.Context, arg DeleteGPXTrackParams) error
	// Limpia los tokens del usuario (logout / desvinculación).
	DeleteStravaTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	// Return the existing row when Strava retries the same natural event key.
	EnqueueActivityEvent(ctx context.Context, arg EnqueueActivityEventParams) (ActivityEvent, error)
	// Devuelve la invitación vigente para un email dado.
	// "Vigente" significa: status pending o accepted, y no expirada
	// (expires_at es NULL o está en el futuro).
	// Usado en el flujo de bloqueo por invitación (v1-phase-1-plan.md §4.7).
	// Puede haber varias vigentes a la vez (una accepted histórica + una pending
	// reenviada): se devuelve la más reciente de forma determinista.
	GetActiveInviteByEmail(ctx context.Context, email string) (GetActiveInviteByEmailRow, error)
	// Búsqueda idempotente por (usuario, fuente, id externo). Es la operación
	// central de la deduplicación: si existe, se actualiza; si no, se inserta.
	GetActivityByExternalID(ctx context.Context, arg GetActivityByExternalIDParams) (Activity, error)
	// Load an event by the internal UUID passed to IngestActivityEventWorker.
	GetActivityEventByID(ctx context.Context, id pgtype.UUID) (ActivityEvent, error)
	GetGPXTrackByHash(ctx context.Context, arg GetGPXTrackByHashParams) (GpxTrack, error)
	GetGPXTrackByID(ctx context.Context, arg GetGPXTrackByIDParams) (GpxTrack, error)
	GetHRZonesByActivity(ctx context.Context, activityID pgtype.UUID) (HrZone, error)
	GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error)
	// Obtiene la sesión de sincronización más reciente del usuario.
	GetLatestSyncSession(ctx context.Context, userID pgtype.UUID) (SyncSession, error)
	// Recupera los tokens OAuth de Strava de un usuario (cifrados).
	GetStravaTokensByUserID(ctx context.Context, userID pgtype.UUID) (StravaToken, error)
	GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error)
	// Obtiene el hr_max del usuario para cálculos de zonas HR.
	GetUserHRMaxByID(ctx context.Context, id pgtype.UUID) (pgtype.Int2, error)
	// The scalar subquery always returns one row. An unknown athlete therefore
	// scans as pgtype.UUID{Valid:false} rather than pgx.ErrNoRows.
	GetUserIDByAthleteID(ctx context.Context, athleteID int64) (pgtype.UUID, error)
	// Lista paginada de actividades del usuario, ordenadas de más reciente a
	// más antigua. El LIMIT es por la query (no cursor) porque el uso esperado
	// es UI paginada con offset; cuando se necesite cursor, se añadirá en su
	// propia query sin tocar esta.
	//
	// COUNT(*) OVER() añade el total real de filas que cumplen el WHERE a
	// cada fila devuelta. El handler coge el valor de la primera fila
	// (es el mismo para todas). issue #172, M6 — antes el handler
	// devolvía `offset + len(rows) (+ 1 si has_next)`, que no es un total.
	ListActivitiesByUser(ctx context.Context, arg ListActivitiesByUserParams) ([]ListActivitiesByUserRow, error)
	ListGPXClimbsByTrack(ctx context.Context, trackID pgtype.UUID) ([]GpxClimb, error)
	ListGPXRiskZonesByTrack(ctx context.Context, trackID pgtype.UUID) ([]GpxRiskZone, error)
	// Misma corrección que ListActivitiesByUser (issue #172, M6):
	// COUNT(*) OVER() añade el total real a cada fila para que el handler
	// pueda devolverlo en `total` sin engañarse con offset+len+1.
	ListGPXTracksByUser(ctx context.Context, arg ListGPXTracksByUserParams) ([]ListGPXTracksByUserRow, error)
	// Lista los eventos pendientes (processed_at IS NULL) para alimentar un
	// job de procesamiento. LIMIT defensivo para evitar scans descontrolados.
	ListPendingActivityEvents(ctx context.Context, limit int32) ([]ActivityEvent, error)
	// Lista las sesiones de sincronización del usuario, más recientes primero.
	ListSyncSessionsByUser(ctx context.Context, arg ListSyncSessionsByUserParams) ([]SyncSession, error)
	// Marca un evento como procesado una vez consumido por el job.
	MarkActivityEventProcessed(ctx context.Context, id pgtype.UUID) error
	MarkInviteAccepted(ctx context.Context, id pgtype.UUID) error
	// Actualiza los contadores de progreso sin tocar status/finished_at.
	UpdateSyncSessionProgress(ctx context.Context, arg UpdateSyncSessionProgressParams) (SyncSession, error)
	// Cambia el estado de la sesión. Si falla el job, se guarda el error.
	UpdateSyncSessionStatus(ctx context.Context, arg UpdateSyncSessionStatusParams) (SyncSession, error)
	UpdateUserInviteStatus(ctx context.Context, arg UpdateUserInviteStatusParams) (User, error)
	// Actualiza las preferencias de entrenamiento e IA del usuario (fase 1.1).
	// Las métricas pueden ir a NULL si el usuario no las conoce; timezone y
	// ai_enabled siempre llevan valor (tienen default en el schema).
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Inserción idempotente de actividad normalizada. Devuelve la fila final
	// (insertada o actualizada) junto con xmax=0 → insert, xmax<>0 → update,
	// expuesto vía RETURNING para que el caller distinga el caso.
	UpsertActivity(ctx context.Context, arg UpsertActivityParams) (Activity, error)
	// Guarda/actualiza un stream concreto de una actividad (HR, watts, ...).
	// PRIMARY KEY (activity_id, stream_type) hace el upsert natural.
	UpsertActivityStream(ctx context.Context, arg UpsertActivityStreamParams) (ActivityStream, error)
	// Idempotente por PK activity_id. Upsert de zonas HR calculadas.
	UpsertHRZones(ctx context.Context, arg UpsertHRZonesParams) (HrZone, error)
	// Inserta o reemplaza los tokens OAuth cifrados de un usuario.
	// Strava solo permite un set de tokens activo por usuario; ON CONFLICT cubre
	// el caso "usuario reconecta" y el refresh que rota access_token.
	UpsertStravaTokens(ctx context.Context, arg UpsertStravaTokensParams) (StravaToken, error)
}

var _ Querier = (*Queries)(nil)
