// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error)
	GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error)
	MarkInviteAccepted(ctx context.Context, id pgtype.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
