// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: strava_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStravaTokensByUserID = `-- name: DeleteStravaTokensByUserID :exec
DELETE FROM strava_tokens
WHERE user_id = $1
`

// Limpia los tokens del usuario (logout / desvinculación).
func (q *Queries) DeleteStravaTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStravaTokensByUserID, userID)
	return err
}

const getStravaTokensByUserID = `-- name: GetStravaTokensByUserID :one
SELECT user_id, access_cipher, refresh_cipher, expires_at, athlete_id, scopes, created_at, updated_at
FROM strava_tokens
WHERE user_id = $1
LIMIT 1
`

// Recupera los tokens OAuth de Strava de un usuario (cifrados).
func (q *Queries) GetStravaTokensByUserID(ctx context.Context, userID pgtype.UUID) (StravaToken, error) {
	row := q.db.QueryRow(ctx, getStravaTokensByUserID, userID)
	var i StravaToken
	err := row.Scan(
		&i.UserID,
		&i.AccessCipher,
		&i.RefreshCipher,
		&i.ExpiresAt,
		&i.AthleteID,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStravaTokens = `-- name: UpsertStravaTokens :one
INSERT INTO strava_tokens (
    user_id, access_cipher, refresh_cipher, expires_at, athlete_id, scopes, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (user_id) DO UPDATE SET
    access_cipher  = EXCLUDED.access_cipher,
    refresh_cipher = EXCLUDED.refresh_cipher,
    expires_at     = EXCLUDED.expires_at,
    athlete_id     = EXCLUDED.athlete_id,
    scopes         = EXCLUDED.scopes,
    updated_at     = now()
RETURNING user_id, access_cipher, refresh_cipher, expires_at, athlete_id, scopes, created_at, updated_at
`

type UpsertStravaTokensParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	AccessCipher  string             `json:"access_cipher"`
	RefreshCipher string             `json:"refresh_cipher"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	AthleteID     int64              `json:"athlete_id"`
	Scopes        string             `json:"scopes"`
}

// Inserta o reemplaza los tokens OAuth cifrados de un usuario.
// Strava solo permite un set de tokens activo por usuario; ON CONFLICT cubre
// el caso "usuario reconecta" y el refresh que rota access_token.
func (q *Queries) UpsertStravaTokens(ctx context.Context, arg UpsertStravaTokensParams) (StravaToken, error) {
	row := q.db.QueryRow(ctx, upsertStravaTokens,
		arg.UserID,
		arg.AccessCipher,
		arg.RefreshCipher,
		arg.ExpiresAt,
		arg.AthleteID,
		arg.Scopes,
	)
	var i StravaToken
	err := row.Scan(
		&i.UserID,
		&i.AccessCipher,
		&i.RefreshCipher,
		&i.ExpiresAt,
		&i.AthleteID,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
