// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSyncSession = `-- name: CreateSyncSession :one
INSERT INTO sync_sessions (user_id, status, window_days)
VALUES ($1, 'pending', $2)
RETURNING id, user_id, status, window_days, total_activities, imported, skipped, error, started_at, finished_at
`

type CreateSyncSessionParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	WindowDays int32       `json:"window_days"`
}

// Crea una nueva sesión de sincronización en estado 'pending'. El caller la
// transita a 'running' con UpdateSyncSessionStatus cuando empieza a procesar.
func (q *Queries) CreateSyncSession(ctx context.Context, arg CreateSyncSessionParams) (SyncSession, error) {
	row := q.db.QueryRow(ctx, createSyncSession, arg.UserID, arg.WindowDays)
	var i SyncSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.WindowDays,
		&i.TotalActivities,
		&i.Imported,
		&i.Skipped,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestSyncSession = `-- name: GetLatestSyncSession :one
SELECT id, user_id, status, window_days, total_activities, imported, skipped, error, started_at, finished_at
FROM sync_sessions
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT 1
`

// Obtiene la sesión de sincronización más reciente del usuario.
func (q *Queries) GetLatestSyncSession(ctx context.Context, userID pgtype.UUID) (SyncSession, error) {
	row := q.db.QueryRow(ctx, getLatestSyncSession, userID)
	var i SyncSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.WindowDays,
		&i.TotalActivities,
		&i.Imported,
		&i.Skipped,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listSyncSessionsByUser = `-- name: ListSyncSessionsByUser :many
SELECT id, user_id, status, window_days, total_activities, imported, skipped, error, started_at, finished_at
FROM sync_sessions
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListSyncSessionsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Lista las sesiones de sincronización del usuario, más recientes primero.
func (q *Queries) ListSyncSessionsByUser(ctx context.Context, arg ListSyncSessionsByUserParams) ([]SyncSession, error) {
	rows, err := q.db.Query(ctx, listSyncSessionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncSession
	for rows.Next() {
		var i SyncSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.WindowDays,
			&i.TotalActivities,
			&i.Imported,
			&i.Skipped,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyncSessionProgress = `-- name: UpdateSyncSessionProgress :one
UPDATE sync_sessions
SET
    total_activities = $2,
    imported         = $3,
    skipped          = $4
WHERE id = $1
RETURNING id, user_id, status, window_days, total_activities, imported, skipped, error, started_at, finished_at
`

type UpdateSyncSessionProgressParams struct {
	ID              pgtype.UUID `json:"id"`
	TotalActivities int32       `json:"total_activities"`
	Imported        int32       `json:"imported"`
	Skipped         int32       `json:"skipped"`
}

// Actualiza los contadores de progreso sin tocar status/finished_at.
func (q *Queries) UpdateSyncSessionProgress(ctx context.Context, arg UpdateSyncSessionProgressParams) (SyncSession, error) {
	row := q.db.QueryRow(ctx, updateSyncSessionProgress,
		arg.ID,
		arg.TotalActivities,
		arg.Imported,
		arg.Skipped,
	)
	var i SyncSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.WindowDays,
		&i.TotalActivities,
		&i.Imported,
		&i.Skipped,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const updateSyncSessionStatus = `-- name: UpdateSyncSessionStatus :one
UPDATE sync_sessions
SET
    status      = $2,
    error       = $3,
    finished_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN now() ELSE finished_at END
WHERE id = $1
RETURNING id, user_id, status, window_days, total_activities, imported, skipped, error, started_at, finished_at
`

type UpdateSyncSessionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	Error  pgtype.Text `json:"error"`
}

// Cambia el estado de la sesión. Si falla el job, se guarda el error.
func (q *Queries) UpdateSyncSessionStatus(ctx context.Context, arg UpdateSyncSessionStatusParams) (SyncSession, error) {
	row := q.db.QueryRow(ctx, updateSyncSessionStatus, arg.ID, arg.Status, arg.Error)
	var i SyncSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.WindowDays,
		&i.TotalActivities,
		&i.Imported,
		&i.Skipped,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
