// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training_load.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listTrainingLoadFromFirstActivity = `-- name: ListTrainingLoadFromFirstActivity :many
SELECT user_id, day, tss, activity_count, distance_m, elevation_gain_m, computed_at
FROM training_load_daily tld
WHERE tld.user_id = $1
  AND tld.day >= COALESCE(
        (SELECT MIN(tld2.day) FROM training_load_daily tld2 WHERE tld2.user_id = $1),
        '0001-01-01'::date
    )
ORDER BY tld.day ASC
`

// Serie completa desde la primera actividad hasta hoy. Usada por el job
// RecalcTrainingLoad cuando no hay `last_recalc_at` registrado.
func (q *Queries) ListTrainingLoadFromFirstActivity(ctx context.Context, userID pgtype.UUID) ([]TrainingLoadDaily, error) {
	rows, err := q.db.Query(ctx, listTrainingLoadFromFirstActivity, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingLoadDaily
	for rows.Next() {
		var i TrainingLoadDaily
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.Tss,
			&i.ActivityCount,
			&i.DistanceM,
			&i.ElevationGainM,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingLoadRange = `-- name: ListTrainingLoadRange :many
SELECT user_id, day, tss, activity_count, distance_m, elevation_gain_m, computed_at
FROM training_load_daily
WHERE user_id = $1
  AND day BETWEEN $2 AND $3
ORDER BY day ASC
`

type ListTrainingLoadRangeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Day    pgtype.Date `json:"day"`
	Day_2  pgtype.Date `json:"day_2"`
}

// Serie diaria en orden cronológico ascendente. Útil para CTL/ATL/TSB
// dashboards: si el rango es anterior a la primera actividad, devuelve 0
// filas (el handler rellena con FillMissingDays, issue #16).
func (q *Queries) ListTrainingLoadRange(ctx context.Context, arg ListTrainingLoadRangeParams) ([]TrainingLoadDaily, error) {
	rows, err := q.db.Query(ctx, listTrainingLoadRange, arg.UserID, arg.Day, arg.Day_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingLoadDaily
	for rows.Next() {
		var i TrainingLoadDaily
		if err := rows.Scan(
			&i.UserID,
			&i.Day,
			&i.Tss,
			&i.ActivityCount,
			&i.DistanceM,
			&i.ElevationGainM,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIDsForTrainingLoadRecalc = `-- name: ListUserIDsForTrainingLoadRecalc :many
SELECT DISTINCT activities.user_id
FROM activities
`

// Para un job fan-out (futuro): lista todos los user_id con actividades
// que requieren recálculo. PR2 no la usa; queda cableada para PR3 o un
// job cron. Mantenerla aquí evita un nuevo PR cuando se encienda.
func (q *Queries) ListUserIDsForTrainingLoadRecalc(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUserIDsForTrainingLoadRecalc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrainingLoadDaily = `-- name: UpsertTrainingLoadDaily :one
INSERT INTO training_load_daily (
    user_id, day, tss, activity_count, distance_m, elevation_gain_m, computed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, day) DO UPDATE SET
    tss              = EXCLUDED.tss,
    activity_count   = EXCLUDED.activity_count,
    distance_m       = EXCLUDED.distance_m,
    elevation_gain_m = EXCLUDED.elevation_gain_m,
    computed_at      = EXCLUDED.computed_at
RETURNING user_id, day, tss, activity_count, distance_m, elevation_gain_m, computed_at
`

type UpsertTrainingLoadDailyParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	Day            pgtype.Date        `json:"day"`
	Tss            float64            `json:"tss"`
	ActivityCount  int32              `json:"activity_count"`
	DistanceM      float64            `json:"distance_m"`
	ElevationGainM float64            `json:"elevation_gain_m"`
	ComputedAt     pgtype.Timestamptz `json:"computed_at"`
}

// Idempotente. Inserta o actualiza la fila diaria de training load para
// (user_id, day). El caller calcula CTL/ATL/TSB; aquí solo persiste TSS +
// KPI crudos.
func (q *Queries) UpsertTrainingLoadDaily(ctx context.Context, arg UpsertTrainingLoadDailyParams) (TrainingLoadDaily, error) {
	row := q.db.QueryRow(ctx, upsertTrainingLoadDaily,
		arg.UserID,
		arg.Day,
		arg.Tss,
		arg.ActivityCount,
		arg.DistanceM,
		arg.ElevationGainM,
		arg.ComputedAt,
	)
	var i TrainingLoadDaily
	err := row.Scan(
		&i.UserID,
		&i.Day,
		&i.Tss,
		&i.ActivityCount,
		&i.DistanceM,
		&i.ElevationGainM,
		&i.ComputedAt,
	)
	return i, err
}
