// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/fgjcarlos/ghamusinos/internal/db/status"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (clerk_user_id, email, display_name, invite_status)
VALUES ($1, $2, $3, $4)
RETURNING id, clerk_user_id, email, display_name, invite_status, created_at, updated_at
`

type CreateUserParams struct {
	ClerkUserID  string              `json:"clerk_user_id"`
	Email        string              `json:"email"`
	DisplayName  pgtype.Text         `json:"display_name"`
	InviteStatus status.InviteStatus `json:"invite_status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClerkUserID,
		arg.Email,
		arg.DisplayName,
		arg.InviteStatus,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.DisplayName,
		&i.InviteStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_user_id, email, display_name, invite_status, created_at, updated_at
FROM users
WHERE clerk_user_id = $1
LIMIT 1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.DisplayName,
		&i.InviteStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    display_name = $2,
    updated_at   = now()
WHERE id = $1
RETURNING id, clerk_user_id, email, display_name, invite_status, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.DisplayName,
		&i.InviteStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
