name: Bug
description: Reportar un comportamiento incorrecto
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Qué falla.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamiento real
      description: Incluye logs o errores si los hay.
    validations:
      required: true
