package auth

import (
	"context"
	"crypto"
	"testing"
	"time"
)

// TEST FIXTURES COMMENT
// These JWT-shaped strings are TEST FIXTURES only. They are not real tokens.
// They use a fake kid ("test-key-1") and signature generated by test key pairs,
// so secret-scanning alerts can be silenced.

// TestJWTValidator_ValidToken tests that a well-formed, valid JWT is accepted.
// SPEC: Scenario "Valid JWT is accepted"
func TestJWTValidator_ValidToken(t *testing.T) {
	kp := GenerateTestKeyPair(t, "test-key-1")
	token := kp.SignToken(t, map[string]interface{}{
		"sub":   "user_123",
		"email": "user@example.com",
		"name":  "Test User",
	}, nil)

	cache := &mockJWKSCache{key: kp.PublicKey}
	validator := NewJWTValidator(cache, "test-audience")

	ctx := context.Background()
	claims, err := validator.Validate(ctx, token)
	if err != nil {
		t.Fatalf("expected validation to succeed, got error: %v", err)
	}

	if claims.Subject != "user_123" {
		t.Errorf("expected Subject='user_123', got '%s'", claims.Subject)
	}
	if claims.Email != "user@example.com" {
		t.Errorf("expected Email='user@example.com', got '%s'", claims.Email)
	}
	if claims.Name != "Test User" {
		t.Errorf("expected Name='Test User', got '%s'", claims.Name)
	}
}

// TestJWTValidator_ExpiredToken tests that a token with exp in the past is rejected.
// SPEC: Scenario "Expired JWT is rejected"
func TestJWTValidator_ExpiredToken(t *testing.T) {
	kp := GenerateTestKeyPair(t, "test-key-1")
	token := kp.SignToken(t,
		map[string]interface{}{
			"sub": "user_123",
		},
		map[string]interface{}{
			"exp": time.Now().Add(-1 * time.Hour).Unix(), // expired 1 hour ago
		})

	cache := &mockJWKSCache{key: kp.PublicKey}
	validator := NewJWTValidator(cache, "test-audience")

	ctx := context.Background()
	_, err := validator.Validate(ctx, token)
	if err != ErrExpiredToken {
		t.Errorf("expected ErrExpiredToken, got: %v", err)
	}
}

// TestJWTValidator_MissingSubClaim tests that a token without sub is rejected.
// SPEC: Scenario "Valid JWT is accepted" (covers missing sub)
func TestJWTValidator_MissingSubClaim(t *testing.T) {
	kp := GenerateTestKeyPair(t, "test-key-1")
	token := kp.SignToken(t,
		map[string]interface{}{ // omit 'sub'
			"email": "user@example.com",
		},
		nil)

	cache := &mockJWKSCache{key: kp.PublicKey}
	validator := NewJWTValidator(cache, "test-audience")

	ctx := context.Background()
	_, err := validator.Validate(ctx, token)
	if err != ErrMissingClaims {
		t.Errorf("expected ErrMissingClaims, got: %v", err)
	}
}

// TestJWTValidator_WrongAudience tests that a token with mismatched aud is rejected.
// SPEC: Scenario "Wrong audience is rejected"
func TestJWTValidator_WrongAudience(t *testing.T) {
	kp := GenerateTestKeyPair(t, "test-key-1")
	token := kp.SignToken(t,
		map[string]interface{}{
			"sub": "user_123",
		},
		map[string]interface{}{
			"aud": "wrong-audience",
		})

	cache := &mockJWKSCache{key: kp.PublicKey}
	validator := NewJWTValidator(cache, "expected-audience")

	ctx := context.Background()
	_, err := validator.Validate(ctx, token)
	if err != ErrMissingClaims {
		t.Errorf("expected ErrMissingClaims for wrong aud, got: %v", err)
	}
}

// TestJWTValidator_InvalidSignature tests that a tampered token is rejected.
// SPEC: Scenario "Invalid signature is rejected"
func TestJWTValidator_InvalidSignature(t *testing.T) {
	kp := GenerateTestKeyPair(t, "test-key-1")
	token := kp.SignToken(t, map[string]interface{}{
		"sub": "user_123",
	}, nil)

	// Generate a different key pair to create an invalid signature
	wrongKp := GenerateTestKeyPair(t, "wrong-key")
	cache := &mockJWKSCache{key: wrongKp.PublicKey}
	validator := NewJWTValidator(cache, "test-audience")

	ctx := context.Background()
	_, err := validator.Validate(ctx, token)
	if err != ErrUnauthenticated {
		t.Errorf("expected ErrUnauthenticated for bad signature, got: %v", err)
	}
}

// TestJWTValidator_MissingNbf tests that a token with nbf in the future is rejected.
// SPEC: Scenario "Valid JWT is accepted" (covers nbf validation)
func TestJWTValidator_MissingNbf(t *testing.T) {
	kp := GenerateTestKeyPair(t, "test-key-1")
	token := kp.SignToken(t,
		map[string]interface{}{
			"sub": "user_123",
		},
		map[string]interface{}{
			"nbf": time.Now().Add(1 * time.Hour).Unix(), // nbf 1 hour in future
		})

	cache := &mockJWKSCache{key: kp.PublicKey}
	validator := NewJWTValidator(cache, "test-audience")

	ctx := context.Background()
	_, err := validator.Validate(ctx, token)
	if err != ErrExpiredToken {
		t.Errorf("expected ErrExpiredToken for future nbf, got: %v", err)
	}
}

// Test helper: mock JWKS cache
type mockJWKSCache struct {
	key crypto.PublicKey
}

func (m *mockJWKSCache) GetKey(ctx context.Context, kid string) (crypto.PublicKey, error) {
	return m.key, nil
}
